# Generated by Django 3.2.4 on 2021-07-10 17:50

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210703_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(re.compile('\\+?\\d\\(?\\d{3}\\)?-?\\d{3}-?\\d{2}-?\\d{2}'), 'Ожидается телефонный номер в формате +7(123)345-6789')], verbose_name='Телефон'),
        ),
    ]
