# Generated by Django 3.2.4 on 2021-07-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_feedback_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-created_at',), 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
