# Generated by Django 3.2.4 on 2021-07-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210627_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(max_length=60, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
