# Generated by Django 3.2.4 on 2021-07-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210703_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(default='undef', max_length=60, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
