# Generated by Django 3.2.4 on 2021-07-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_producttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Показывать продукт'),
        ),
    ]
